-- admin query
CREATE TABLE ADMIN (
    AID VARCHAR2(50) PRIMARY KEY,
    APW VARCHAR2(50) NOT NULL,
    ANAME VARCHAR2(50) NOT NULL,
    AGROUP VARCHAR2(200) NOT NULL,
    ARDATE DATE DEFAULT SYSDATE NOT NULL
    );

INSERT INTO ADMIN VALUES('admin', '1', '관리자', '관리부', SYSDATE);
COMMIT;
SELECT * FROM ADMIN;
