-- 날짜 출력 ID = getCampDate
SELECT RESDATE FROM RESERVED WHERE CAMPNO = 100;

-- 날짜 선택 시 예약 가능한지(REM > 0) ID = getCampDateRem
SELECT RESDATE, REM FROM RESERVED WHERE CAMPNO = 108 AND REM > 0 AND TO_CHAR(RESDATE, 'YYYY-MM-DD') = '2023-12-03';

-- 중복된 날짜로 예약된 기록이 있는지 ID =  getCampBookingDate
SELECT * FROM BOOKING WHERE BDATE = '2023-12-02' AND ID = 'ccc';

-- 예약 처리 ID = reservationCamp
INSERT INTO BOOKING (BNO, ID, CAMPNO, STATUS, BDATE) VALUES (BOOKING_SQ.NEXTVAL, 'test', 100, 1, '2023-11-24');

-- 예약 성공 시 예약가능한 잔여수 하나빼기 ID = remMinus
UPDATE RESERVED SET REM = REM - 1 WHERE CAMPNO = 100 AND RESDATE = '2023-11-24';

-- 예약 정보 출력 ID = getBookingInfo
SELECT * FROM BOOKING WHERE ID = 'test';

SELECT A.*, B.CAMPNAME, B.PARKNAME, B.CAMPADDRESS, B.CAMPTEL FROM BOOKING A, CAMP B WHERE A.CAMPNO=B.CAMPNO AND ID = 'test';

SELECT 
	    A.*, 
	    B.PARKNAME AS CAMP_PARKNAME, b.CAMPNAME, 
	    C.PARKNAME AS SHELTER_PARKNAME, c.SHELTERNAME,
	    D.PARKNAME AS EXPLORE_PARKNAME, d.EXPLORENAME
			FROM BOOKING A
			LEFT JOIN CAMP B ON A.CAMPNO = B.CAMPNO
			LEFT JOIN SHELTER C ON A.SHELTERNO = C.SHELTERNO
			LEFT JOIN EXPLORE D ON A.EXPLORENO = D.EXPLORENO
			WHERE A.ID = 'test';

-- 예약 취소 ID = cancleReservation
UPDATE BOOKING SET STATUS = 0 WHERE BNO = 1;

-- 예약 취소 시 예약가능한 잔여수 하나추가 ID = remPlus
UPDATE RESERVED SET REM = REM + 1 WHERE CAMPNO = 100 AND RESDATE = '2023-11-29';

-- 대피소 리스트 출력 ID =  getShelterList
SELECT SHELTERNO, SHELTERNAME FROM SHELTER WHERE PARKNAME = '지리산';

-- 대피소 예약 가능 여부
SELECT RESDATE FROM RESERVED WHERE SHELTERNO = 200 AND REM > 0 AND RESDATE = '2023-11-28';

SELECT * FROM SHELTER;

-- 관리자 예약 현황
SELECT 
    A.*, 
    B.PARKNAME AS CAMP_PARKNAME, b.CAMPNAME, 
    C.PARKNAME AS SHELTER_PARKNAME, c.SHELTERNAME,
    D.PARKNAME AS EXPLORE_PARKNAME, d.EXPLORENAME,
    E.NAME
		FROM BOOKING A
		LEFT JOIN CAMP B ON A.CAMPNO = B.CAMPNO
		LEFT JOIN SHELTER C ON A.SHELTERNO = C.SHELTERNO
		LEFT JOIN EXPLORE D ON A.EXPLORENO = D.EXPLORENO
    LEFT JOIN MEMBER E ON A.ID = E.ID
		WHERE B.PARKNAME = '설악산' OR C.PARKNAME = '설악산' OR D.PARKNAME = '설악산';




-- ☆ 2023-11-30 변경할 Query(검색추가)
-- [관리자] 예약 날짜 출력 id = reservedList
SELECT 
    A.*, 
    B.PARKNAME AS CAMP_PARKNAME, b.CAMPNAME, 
    C.PARKNAME AS SHELTER_PARKNAME, c.SHELTERNAME,
    D.PARKNAME AS EXPLORE_PARKNAME, d.EXPLORENAME
FROM RESERVED A
LEFT JOIN CAMP B ON A.CAMPNO = B.CAMPNO
LEFT JOIN SHELTER C ON A.SHELTERNO = C.SHELTERNO
LEFT JOIN EXPLORE D ON A.EXPLORENO = D.EXPLORENO
WHERE 
    A.RESDATE >= TRUNC(SYSDATE)
    AND (B.PARKNAME = '설악산' OR C.PARKNAME = '설악산' OR D.PARKNAME = '설악산');

      
SELECT 
	    A.*, 
	    B.PARKNAME AS CAMP_PARKNAME, b.CAMPNAME, 
	    C.PARKNAME AS SHELTER_PARKNAME, c.SHELTERNAME,
	    D.PARKNAME AS EXPLORE_PARKNAME, d.EXPLORENAME
			FROM RESERVED A
			LEFT JOIN CAMP B ON A.CAMPNO = B.CAMPNO
			LEFT JOIN SHELTER C ON A.SHELTERNO = C.SHELTERNO
			LEFT JOIN EXPLORE D ON A.EXPLORENO = D.EXPLORENO
			WHERE (B.PARKNAME = '설악산' OR C.PARKNAME = '설악산' OR D.PARKNAME = '설악산') AND TO_CHAR(RESDATE, 'YYYY-MM-DD') = '2023-12-02';

SELECT * FROM RESERVED;

-- [관리자] 예약조정 ID = reservedRemControl
UPDATE RESERVED SET REM = 10 WHERE RESNO = 1 AND RESDATE = '2023-11-24';

-- ☆ 2023-11-30 등록할 Query
-- [관리자] 예약일자 등록처리[당일]
-- CAMP [type = camp]
INSERT INTO RESERVED (RESNO, CAMPNO, RESDATE, REM) VALUES (RESERVED_SQ.NEXTVAL, 100, SYSDATE, 20);
-- SHELTER [type = shelter]
INSERT INTO RESERVED (RESNO, SHELTERNO, RESDATE, REM) VALUES (RESERVED_SQ.NEXTVAL, 200, SYSDATE, 20);
-- [관리자] 예약일자 등록처리[익일]
-- CAMP [type = camp]
INSERT INTO RESERVED (RESNO, CAMPNO, RESDATE, REM) VALUES (RESERVED_SQ.NEXTVAL, 100, SYSDATE+1, 20);
-- SHELTER [type = shelter]
INSERT INTO RESERVED (RESNO, SHELTERNO, RESDATE, REM) VALUES (RESERVED_SQ.NEXTVAL, 200, SYSDATE+1, 20);
-- [관리자] 예약일자 등록처리[지정일]
-- CAMP [type = camp]
INSERT INTO RESERVED (RESNO, CAMPNO, RESDATE, REM) VALUES (RESERVED_SQ.NEXTVAL, 100, '2023-12-04', 20);
-- SHELTER [type = shelter]
INSERT INTO RESERVED (RESNO, SHELTERNO, RESDATE, REM) VALUES (RESERVED_SQ.NEXTVAL, 200, '2023-12-01', 20);
-- [관리자] 날짜 등록 여부 조회
SELECT COUNT(*) FROM RESERVED WHERE CAMPNO = 108 AND TO_CHAR(RESDATE, 'YYYY-MM-DD') = '2023-12-02';
SELECT COUNT(*) FROM RESERVED WHERE SHELTERNO = 200 AND RESDATE = '2023-11-30';

DELETE FROM RESERVED WHERE CAMPNO = 100 AND TO_CHAR(RESDATE, 'YYYY-MM-DD') = '2023-11-24';

COMMIT;