-- DROP TABLE 
DROP TABLE RESERVED;
DROP TABLE BOOKING;
DROP TABLE CAMP;
DROP TABLE SHELTER;
DROP TABLE EXPLORE;

-- DROP SEQUENCE
DROP SEQUENCE CAMP_SQ;
DROP SEQUENCE SHELTER_SQ;
DROP SEQUENCE EXPLORE_SQ;
DROP SEQUENCE RESERVED_SQ;

-- CREATE SEQUENCE [CAMP : 100~199, SHELTER : 200~299, EXPLORE : 300~399]
CREATE SEQUENCE CAMP_SQ MINVALUE 100 MAXVALUE 199 NOCYCLE NOCACHE;
CREATE SEQUENCE SHELTER_SQ MINVALUE 200 MAXVALUE 299 NOCYCLE NOCACHE;
CREATE SEQUENCE EXPLORE_SQ MINVALUE 300 MAXVALUE 399 NOCYCLE NOCACHE;
CREATE SEQUENCE RESERVED_SQ MAXVALUE 999999 NOCYCLE NOCACHE;
CREATE SEQUENCE BOOKING_SQ MAXVALUE 999999 NOCYCLE NOCACHE;

-- CREATE TABLE
CREATE TABLE CAMP (
  CAMPNO NUMBER(3) PRIMARY KEY,
  CAMPNAME VARCHAR2(200) NOT NULL,
  PARKNAME VARCHAR2(50) REFERENCES PARK(PARKNAME) NOT NULL,
  CAMPADDRESS VARCHAR2(200) NOT NULL,
  CAMPTEL VARCHAR2(20) NOT NULL
);

CREATE TABLE SHELTER (
  SHELTERNO NUMBER(3) PRIMARY KEY,
  SHELTERNAME VARCHAR2(200) NOT NULL,
  PARKNAME VARCHAR2(50) REFERENCES PARK(PARKNAME) NOT NULL,
  SHELTERADDRESS VARCHAR2(200) NOT NULL,
  SHELTERTEL VARCHAR2(20) NOT NULL
);

CREATE TABLE EXPLORE (
  EXPLORENO NUMBER(3) PRIMARY KEY,
  EXPLORENAME VARCHAR2(200) NOT NULL,
  PARKNAME VARCHAR2(50) REFERENCES PARK(PARKNAME) NOT NULL,
  EXPLOREADDRESS VARCHAR2(200) NOT NULL,
  EXPLORETEL VARCHAR2(20) NOT NULL
);

CREATE TABLE RESERVED (
  RESNO NUMBER(6) PRIMARY KEY,
  CAMPNO NUMBER(3) REFERENCES CAMP(CAMPNO),
  SHELTERNO NUMBER(3) REFERENCES SHELTER(SHELTERNO),
  EXPLORENO NUMBER(3) REFERENCES EXPLORE(EXPLORENO),
  RESDATE DATE NOT NULL,
  REM NUMBER(3) DEFAULT 20 NOT NULL
);

CREATE TABLE BOOKING (
  BNO NUMBER(6) PRIMARY KEY,
  ID VARCHAR2(50) REFERENCES MEMBER(ID) NOT NULL,
  CAMPNO NUMBER(3) REFERENCES CAMP(CAMPNO),
  SHELTERNO NUMBER(3) REFERENCES SHELTER(SHELTERNO),
  EXPLORENO NUMBER(3) REFERENCES EXPLORE(EXPLORENO),
  STATUS NUMBER(2) NOT NULL,
  BDATE DATE NOT NULL
);
