
CREATE TABLE MEMBER (
    ID VARCHAR2(50) PRIMARY KEY,
    PW VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    PHONE VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    GENDER VARCHAR2(5) NOT NULL,
    BIRTH DATE NOT NULL,
    MRDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE ADMIN (
    AID VARCHAR2(50) PRIMARY KEY,
    APW VARCHAR2(50) NOT NULL,
    ANAME VARCHAR2(50) NOT NULL,
    AGROUP VARCHAR2(200) NOT NULL,
    ARDATE DATE DEFAULT SYSDATE NOT NULL
    );
INSERT INTO ADMIN VALUES('admin', '1', '관리자', '관리부', SYSDATE);
SELECT * FROM ADMIN;

CREATE TABLE SUGGEST (
    SNO NUMBER(6) PRIMARY KEY,              -- 글번호
    ID VARCHAR2(50) REFERENCES MEMBER(ID),  -- 회원ID
    AID VARCHAR2(50) REFERENCES ADMIN(AID), -- 관리자ID
    STITLE VARCHAR2(200) NOT NULL,          -- 글제목
    STEXT CLOB NOT NULL,                    -- 글내용
    SRDATE DATE DEFAULT SYSDATE NOT NULL,   -- 글작성 시점
    SHIT NUMBER(5) DEFAULT 0,                -- 글 조회수
    SGROUP NUMBER(5) NOT NULL,              -- 글 그룹(원글의 경우 글번호로/답변글일경우 원글의 SGROUP으로)
    SSTEP NUMBER(5) NOT NULL,               -- 글그룹내 출력 순서(원글 0)     
    SINDENT NUMBER(5) NOT NULL,             -- 글 LIST 출력시 글 제목 들여쓰기 정도(원글0)
    SIP VARCHAR2(20) NOT NULL               -- 글 쓴 컴퓨터의 IP
);
CREATE SEQUENCE SUGGEST_SQ MAXVALUE 999999 NOCYCLE NOCACHE;
COMMIT;


-- dummy data (3개 이상 - 2개원글+1개답변글)
INSERT INTO SUGGEST (SNO, ID, STITLE, STEXT, SRDATE, SGROUP, SSTEP, SINDENT, SIP)
  VALUES (SUGGEST_SQ.NEXTVAL, 'aaa', '예약을 쉽게', '하는방법', SYSDATE, SUGGEST_SQ.CURRVAL, 0,0, '192.168.0.254');--글1
INSERT INTO SUGGEST (SNO, ID, STITLE, STEXT, SRDATE, SGROUP, SSTEP, SINDENT, SIP)
  VALUES (SUGGEST_SQ.NEXTVAL, 'bbb', '가는길', '알려주세요', SYSDATE, SUGGEST_SQ.CURRVAL, 0,0, '192.168.0.253');--글2
INSERT INTO SUGGEST (SNO, ID, STITLE, STEXT, SRDATE, SGROUP, SSTEP, SINDENT, SIP)
  VALUES (SUGGEST_SQ.NEXTVAL, 'ddd', '주차가', '힘들어요', SYSDATE, SUGGEST_SQ.CURRVAL, 0,0, '192.168.0.252');--글3  
INSERT INTO SUGGEST (SNO, AID, STITLE, STEXT, SRDATE, SGROUP, SSTEP, SINDENT, SIP)
  VALUES (SUGGEST_SQ.NEXTVAL, 'admin', '주차를 ', '쉽게하는방법', SYSDATE, 3, 1, 1, '192.168.0.200');--글3 답변

DELETE FROM SUGGEST WHERE SNO=4;

SELECT * FROM SUGGEST ORDER BY SGROUP DESC, SSTEP; -- 확인

-- Suggest.xml에 들어갈 query
-- 1. 글목록(startRow부터 endRow) id=suggestList
-- WRITER 타이틀에 작성자이름(사용자가 썼으면 사용자이름, 관리자가 썼으면 관리자 이름) 출력
--SELECT SNO, (SELECT NAME FROM MEMBER WHERE SUGGEST.ID=ID)||
--  (SELECT ANAME FROM ADMIN WHERE SUGGEST.AID=AID) WRITER, STITLE, SHIT, SRDATE 
--  FROM SUGGEST ORDER BY SRDATE DESC; 
  
-- WRITER 타이틀에 사용자가 썼으면 사용자이름, 관리자가 썼으면 관리자라고 출력
--SELECT SNO, (SELECT NAME FROM MEMBER WHERE SUGGEST.ID=ID)||
--  (SELECT '관리자' FROM ADMIN WHERE SUGGEST.AID=AID) WRITER, STITLE, SHIT, SRDATE 
--  FROM SUGGEST ORDER BY SRDATE DESC;
--SELECT SNO, NVL((SELECT NAME FROM MEMBER WHERE SUGGEST.ID=ID), '관리자') WRITER, STITLE, SHIT, SRDATE 
--  FROM SUGGEST ORDER BY SRDATE DESC;

SELECT *
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT SNO, NVL((SELECT NAME FROM MEMBER WHERE SUGGEST.ID=ID), '관리자') WRITER, STITLE, SHIT, SRDATE, SINDENT, SSTEP 
        FROM SUGGEST ORDER BY SGROUP DESC, SSTEP) A)
    WHERE RN BETWEEN 1 AND 20;
  
-- 2. 글갯수 id=getSuggestTotCnt
SELECT COUNT(*) CNT FROM SUGGEST;

-- 3. 원글쓰기 id=suggestInsert
INSERT INTO SUGGEST (SNO, ID, STITLE, STEXT, SRDATE, SGROUP, SSTEP, SINDENT, SIP)
  VALUES (SUGGEST_SQ.NEXTVAL, 'aaa', '난방', '개별난방을 해주세요', SYSDATE, SUGGEST_SQ.CURRVAL, 0,0, '192.168.0.254');--글1
  
-- 4. bid로 조회수 1 올리기 id=suggestHitUp
UPDATE SUGGEST SET SHIT = SHIT+1 WHERE SNO=8;

-- 5. bid로 dto가져오기 id=getSuggest
SELECT * FROM SUGGEST WHERE SNO=9;

-- 6. 글수정 id=suggestModify
UPDATE SUGGEST 
    SET ID = 'bbb',
        AID = null,
        STITLE = '가까운',
        STEXT = '주차장',
        SIP = '192.168.0.190'
    WHERE SNO = 10;
    
COMMIT;        
-- 7. 글삭제 id=suggestDelete
DELETE FROM SUGGEST WHERE SNO=3;
ROLLBACK;

COMMIT;
SELECT * FROM SUGGEST;

-- 8. 답변글 저장 전단계(엑셀 ⓐ단계) :  id=suggestPreReplyStep
SELECT * FROM SUGGEST WHERE SNO=5;
UPDATE SUGGEST SET SSTEP = SSTEP+1 WHERE SGROUP=8 AND SSTEP > 1;

-- 9. 답변글 저장 (원글의 SGROUP=2, SSTEP=1, SINDENT=1) id=uggestReplyInsert
INSERT INTO SUGGEST (SNO, AID, STITLE, STEXT, SRDATE, SGROUP, SSTEP, SINDENT, SIP)
  VALUES (SUGGEST_SQ.NEXTVAL, 'admin', '난방을 ', '개별난방으로', SYSDATE, 8, 1, 1, '192.168.0.200');

COMMIT;
SELECT * FROM SUGGEST ORDER BY SGROUP DESC, SSTEP; -- 확인



